
FROM r-base:3.6.1
#
RUN apt-get update --fix-missing && apt-get install -y procps wget bzip2 ca-certificates libglib2.0-0 libxext6 libsm6 libxrender1 git mercurial subversion build-essential libcurl4-gnutls-dev libssl-dev libxml2-dev libhdf5-dev

RUN apt-get install mcl datamash

RUN Rscript -e 'install.packages(c("data.table", "dplyr", "Matrix", "stringr", "cowplot", "RColorBrewer", "ggpubr", "proxy", "irlba", "umap", "gplots", "Seurat"), dependencies = TRUE)'

# Install Bioconductor packages, nothing for now.
RUN Rscript -e 'BiocManager::install(c())'
RUN Rscript -e 'BiocManager::install("multtest")'

sudo apt-get install -y \
    libssl-dev \
    libhdf5-dev \
    libcurl4-openssl-dev
RUN Rscript -e 'BiocManager::install("Seurat")'

# install github packages
RUN Rscript -e 'devtools::install_github(c("caleblareau/BuenColors"))'



